<?php

namespace Xgbnl\Business\Facades;

use Illuminate\Support\Facades\Facade;

class BusinessFacade extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'business'; // TODO: Change the autogenerated stub
    }
}
