<?php

namespace Xgbnl\Business\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Xgbnl\Business\Traits\BusinessGenerator;

abstract class AbstractController extends Controller
{
    use BusinessGenerator;

    protected ?Request $request = null;

    public function callAction($method, $parameters)
    {
        $injected = false;

        foreach ($parameters as $p) {
            if ($p instanceof Request) {
                $this->request = $p;
                $injected      = true;
            }
        }

        if (!$injected) {
            $this->request = \request();
        }

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}
