<?php

namespace Xgbnl\Business\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use ReflectionException;
use Xgbnl\Business\Traits\BusinessGenerator;
use Xgbnl\Business\Traits\ReflectionParse;
use Xgbnl\Business\Utils\MagicMethods;
use ReflectionClass;

abstract class AbstractController extends Controller
{
    use BusinessGenerator,ReflectionParse;

    protected ?Request $request = null;

    public function callAction($method, $parameters)
    {
        $injected = false;

        foreach ($parameters as $p) {
            if ($p instanceof Request) {
                $this->request = $p;
                $injected      = true;
            }
        }

        if (!$injected) {
            $this->request = \request();
        }

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    /**
     * @throws ReflectionException
     */
    public function __call($method, $parameters)
    {
        $reflection = new ReflectionClass(MagicMethods::class);
        if (!$reflection->hasMethod($method)) {
            parent::__call($method, $parameters);
        }

        return $this->parseMethod($reflection, $method, $parameters);
    }
}
