<?php

namespace Xgbnl\Business\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Xgbnl\Business\Attributes\Business;
use Xgbnl\Business\Traits\BusinessGenerator;
use Xgbnl\Business\Traits\ReflectionParse;
use Xgbnl\Business\Utils\MagicMethods;

#[Business(MagicMethods::class)]
abstract class AbstractController extends Controller
{
    use BusinessGenerator,ReflectionParse;

    protected ?Request $request = null;

    public function callAction($method, $parameters)
    {
        $injected = false;

        foreach ($parameters as $p) {
            if ($p instanceof Request) {
                $this->request = $p;
                $injected      = true;
            }
        }

        if (!$injected) {
            $this->request = \request();
        }

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}
